name: Continuous Integration
on: [push, pull_request]

jobs:

  build:
    name: Build + Test (${{matrix.operating-system}})
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operating-system}}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: ./.github/actions/setup-java
    - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
    - run: ./gradlew build

  update-dependency-graph:
    name: Update dependency graph
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: ./.github/actions/setup-java
    - uses: gradle/actions/dependency-submission@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
